services:
  app:
    context: ./
    primary: true
    exposePort: 3000
    environment:
      - name: MOCK_DEPLOYMENT
        value: 1
      - name: VOYAGE_SERVICE_API_URL
        value: ${VOYAGE_SERVICE_API_URL}
  api:
    context: ./
    externalUrl: https://github.com/voyage-playground/user-app-api
    exposePort: 3001
    environment:
      - name: PORT
        value: '3001'
