services:
  app:
    build: ./
    primary: true
    exposePort: 3000
    environment:
      - name: MOCK_DEPLOYMENT
        value: 1
  api:
    build: ./
    externalUrl: https://github.com/voyage-playground/user-app-api
    externalBranch: master
    exposePort: 3001
    environment:
      - name: PORT
        value: '3001'
